name: soft_school
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.3.2

flutter:
  uses-material-design: true
  fonts:
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-VariableFont_wght.ttf
          weight: 400
  assets:
    - assets/images/softy.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#42C8FF"
  image: assets/images/softy.png
  android: true
  ios: true
  web: false